### ISSUE TITLE
[Setting] 이슈 및 PR 템플릿을 추가합니다. 

### ISSUE THREAD

**Issue by compuTasha** [extreme-rock/GetARock-iOS#1]
## 💡 Issue
이슈 및 PR 템플릿을 추가합니다. 

## 📝  todo
- [x] 일반 이슈 템플릿 추가
- [x] 버그 리포트 템플릿 추가
- [x] PR 템플릿 추가
