### ISSUE TITLE
[Feat] 내 밴드 삭제하기 기능과 관련 UI를 추가합니다. 

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#100]
#### 밴드를 삭제할 수 있는 기능과 UI를 구현합니다.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/103009135/218369726-fec5bdea-6640-4ad5-a123-cde0ae17e30c.png">

## 📝  todo
- [ ] 밴드 삭제관련 UI 구현
- [ ] 삭제 alert 및 네트워크 코드 추가
- [ ] 세부 UI 조정
