### ISSUE TITLE
[Feat] 설정 페이지 각 항목에 해당하는 외부 사이트를 연결합니다.

### ISSUE THREAD

**Issue by compuTasha** [extreme-rock/GetARock-iOS#108]
## 💡 Issue
<img width="492" alt="image" src="https://user-images.githubusercontent.com/51108729/218383441-9b2c993f-82a4-4b9d-ae06-95b34ee20dd8.png">

## 📝  todo
- [x] 약관 및 정책 노션 연결
- [x] 서드파티 정보 노션 연결
- [x] 문의하기 이메일 연결
