### ISSUE TITLE
[Setting] Certificate, Provisioning profile을 생성합니다.

### ISSUE THREAD

**Issue by compuTasha** [extreme-rock/GetARock-iOS#119]
## 💡 Issue
팀 세팅을 위한 작업인 Certificate 인증서 및 Provisioning profile을 생성하고 등록합니다.

## 📝  todo
- [x] 기존 앱 권한 변경
- [x] 개인 개발자 계정에 팀원 초대
- [x] Certificates 생성
- [x] Apple Developer 사이트에 App 등록
- [x] Device 등록 (UDID 등록)
- [x] Provisioning Profiles 생성

**Comment by compuTasha** [comment]
Xcode 클라우드 빌더 추가 완료
