### ISSUE TITLE
[Setting] Push Notification 설정 

### ISSUE THREAD

**Issue by compuTasha** [extreme-rock/GetARock-iOS#142]
## 💡 Issue
Apple Notification Server 를 사용하기 위한 기본 설정을 합니다.

## 📝  todo
- [x] Identifiers에 push notification 등록
- [x] xcode에서 capabilities 추가
- [x] 앱 런치 시 device token 저장
- [x] 저장에 성공하면 서버에 전송
