### ISSUE TITLE
[Design] 메인으로 사용하는 지도 뷰 UI를 구성합니다. 

### ISSUE THREAD

**Issue by compuTasha** [extreme-rock/GetARock-iOS#20]
## 💡 Issue
메인으로 사용하는 지도 뷰 UI를 구성합니다.  

<img src="https://user-images.githubusercontent.com/51108729/213517957-8e3d1069-f8b8-4c50-a82e-c9ded053f617.png" width="300"> 

## 📝  todo
- [x] 지도 뷰 구현 - 구글맵
- [x] 버튼 UI 구현
- [x] 임시 텍스트라벨 추가
