### ISSUE TITLE
[Design] 기본 TextView UI를 구현합니다. 

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#26]
## 💡 Issue
회원가입, 밴드생성, 모여락 소개 등에 사용되는 기본 텍스트 필드를 구현합니다.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/103009135/213630969-1d665d9f-2262-481c-b18d-9492a0344761.png">

## 📝  todo
- [ ] 텍스트 필드 기본 UI 구현
- [ ] 글자수 세기 UI 구현
- [ ] 글자수 세기 로직 구현
