### ISSUE TITLE
[Design] 밴드 생성과 관련된 View들의 UI를 구현합니다.

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#27]
### 밴드 생성시 유저는 밴드의 정보를 입력하게 됩니다. 그와 관련된 View의 Layout 및 UI 작업을 진행합니다.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/103009135/213631545-292988d4-e81b-4f79-9682-115b753f2b95.png">

## 📝  todo
- [ ] scrollView 및 contentView + stack으로 Layout잡기
- [ ] contentView내 필요한 UIView들 프로퍼티로 선언
- [ ] 합주실 위치 선정 주소 검색 UI 구현
- [ ] 합주곡 추가 UI 구현 (TableView 추가)
- [ ] SNS 선택 관련 UI 구현

- [ ] 합주실 위치 선정 로직 추가 및 VC간 데이터 전달 로직 구현
- [ ] 합주실 위치 선정 로직 추가 및 VC간 데이터 전달 로직 구현
