### ISSUE TITLE
[Design] 내 위치, 밴드, 모여락을 표시할 커스텀 마커를 구현합니다. 

### ISSUE THREAD

**Issue by compuTasha** [extreme-rock/GetARock-iOS#38]
## 💡 Issue
내 위치, 밴드, 모여락을 표시할 커스텀 마커를 구현합니다.   

<img src="https://user-images.githubusercontent.com/51108729/213517957-8e3d1069-f8b8-4c50-a82e-c9ded053f617.png" width="300"> 

## 📝  todo
- [x] 내 위치 커스텀 마커 구현
- [x] 밴드 커스텀 마커 구현
- [x] 모여락 커스텀 마커 구현 
- [x] 마커 지도에 반영
- [x] 밴드 마커 선택 시 마커 모양 변경
