### ISSUE TITLE
[Design] 모여락 생성과 관련된 뷰의 UI를 구성합니다.

### ISSUE THREAD

**Issue by compuTasha** [extreme-rock/GetARock-iOS#60]
## 💡 Issue

모여락 생성 시 사용하는 뷰의 layout 및 UI를 작업합니다.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/51108729/215277775-c3c6543f-0e66-4e88-94ca-3571f99499f1.png">

## 📝  todo
- [ ] 스크롤뷰 layout 
- [ ] 공통 컴포넌트 적용 (모여락 제목, 모여락 이유, 모여락 소개)
- [ ] 루키 선생님의 합주실 위치 뷰 연결
- [ ] 데이트 픽커 커스텀
