### ISSUE TITLE
[Design] 밴드 생성하기 작업 중 리더의 포지션을 선택하는 View의 UI를 구현합니다.

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#82]
#### 아래 사진에 나온 View의 UI를 구현합니다

![Image](https://user-images.githubusercontent.com/103009135/218292937-73e96acb-5970-4a8b-a628-2343e50cfa03.png)

## 📝  todo

- [ ] CollectionView 활용한 기본 레이아웃 UI 구현
- [ ] BandData 모델 생성 및 전달 기본 구조 잡기
- [ ] Navigation 기능 구현
