### ISSUE TITLE
[Design] 밴드 생성하기에서 밴드 구성원 추가 기능과 관련 UI를 구현합니다. 

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#83]
## 💡 Issue
밴드를 생성할 때 구성원을 추가하고 삭제할 수 있어야합니다. 아래에 보이는 view들과 관련 기능을 개발합니다
<img width="721" alt="image" src="https://user-images.githubusercontent.com/103009135/218298283-9d5389f9-f054-4889-8e71-88a8e457989e.png">

## 📝  todo

- [ ] 밴드 구성원 추가 기본 UI 작업
- [ ] 밴드 멤버 검색 관련 UI 작업
- [ ] 미가입 멤버 추가 기능
- [ ] 밴드 리더 설정 및 설명 view 구현
