### ISSUE TITLE
[Design] 마이페이지 상세 UI 를 제작합니다.

### ISSUE THREAD

**Issue by GODNOEL** [extreme-rock/GetARock-iOS#90]
## 💡 Issue
마이페이지 상세페이지 UI를 제작합니다.
앞써 제작한 상세페이지 틀과 공통컴포넌트를 이용해 UI를 제작합니다.

 | 구분 | 밴드정보 | 타임라인 | 방명록 | 
  |:---|:---:|:---:|:---:|
  | 이미지  |<img width="200" alt="image" src="https://user-images.githubusercontent.com/103012104/218306079-bbaa7010-adf4-4e74-9e72-30cb3a200113.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/103012104/218306090-23072910-9a38-45f7-9078-048a9cf3f028.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/103012104/218306099-fc31829d-c361-4694-9d6f-badeb00b930f.png"> | 

## 📝  todo
- [x] 마이페이지 UI 제작
- [ ] 로그인 권한에 따른 세그먼트 컨트롤 분기처리
- [ ] 유저의 소속밴드 dropdown으로 노출

**Comment by GODNOEL** [comment]
1차 배포때는 모여락을 빼고 진행해서 아래기능은 빼고 진행합니다.
- 타임라인
- 내가 댓글 쓴 모여락
