### ISSUE TITLE
[Design] 밴드 생성하기에서 밴드 정보를 입력하는 UI를 구현합니다.

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#94]
#### 아래와 같이 밴드 정보를 생성하는데 사용되는 UI를 구현합니다 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/103009135/218364968-433c4f55-9780-44d1-98d7-a0fb13ef5d9e.png">

## 📝  todo
- [x] ScrollView + StackView 기반 레이아웃잡기
- [x] ContentView에 사용되는 하위 뷰 삽입
- [x] 세부 디테일 UI 수정
