### ISSUE TITLE
[Feat] 밴드 정보 입력에서 합주실 위치와 합주곡을 추가하는 기능을 구현합니다.

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#95]
## 💡 Issue
합주실 위치 및 합주곡 추가는 새로운 View Controller에 구현해야하기 때문에 기본 UI와 같이 작업하기에는 코드량이 커집니다.
그래서 기본 디자인과 합주 장소 및 합주곡 추가 기능을 구분하여 진행합니다.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/103009135/218366394-1ac1e264-4235-47ce-b1cf-a61c70a67681.png">

## 📝  todo
- [ ] 합주실 위치 VC  생성 및 데이터 전달
- [ ] 합주곡 추가 VC 생성
- [ ] 세부 UI 수정
- [ ] 데이터 전달 테스트
- [ ] POST 할 데이터 모델 작성
