### ISSUE TITLE
[Feat] 밴드 초대 수락과 거절에서 PUT 요청 기능을 구현합니다.

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#97]
#### 알림함에서 밴드 초대를 수락하면, 서버 측으로 수락했다는 request(PUT)를 보내고 응답을 받아와 다른 View로 전환됩니다.
그와 관련된 기능과 UI를 구현합니다.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/103009135/218367577-f283e89a-4dcd-49ed-868c-cafc34525638.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/103009135/218367966-622b3aa8-461e-47eb-8663-693ae8d75447.png">

## 📝  todo
- [ ] 수락 버튼에 PUT요청 처리
- [ ] 초대수락시 이동되는 포지션 선택 VC 구현
- [ ] 가입하기 버튼 후 안내창으로 navigation
- [ ] 거절 하기 버튼에 alert 추가
- [ ] 거절하기 확인시 PUT 요청 처리
- [ ] 거절에 따른 Cell UI 업데이트
